In [1]:
import numpy as np

array_from_list = np.array([1, 2, 3, 4, 5])
print(array_from_list)

array_from_tuple = np.array((10, 20, 30, 40, 50))
print(array_from_tuple)

array_arange = np.arange(10)
print(array_arange)

array_arange_step = np.arange(0, 10, 2)
print(array_arange_step)

array_linspace = np.linspace(0, 10, 5)
print(array_linspace)

array_linspace_2 = np.linspace(1, 2, 4)
print(array_linspace_2)

array_zeros = np.zeros(5)
print(array_zeros)

array_zeros_2d = np.zeros((3, 3))
print(array_zeros_2d)

array_ones = np.ones(4)
print(array_ones)

array_ones_2d = np.ones((2, 3))
print(array_ones_2d)

array_empty = np.empty((2, 2))
print(array_empty)

array_empty_1d = np.empty(3)
print(array_empty_1d)

identity_matrix = np.eye(3)
print(identity_matrix)

random_array = np.random.rand(2, 3)
print(random_array)

random_int_array = np.random.randint(1, 10, size=(3, 3))
print(random_int_array)

random_normal_array = np.random.randn(2, 2)
print(random_normal_array)

array_full = np.full((3, 3), 7)
print(array_full)

array_tile = np.tile([1, 2], 3)
print(array_tile)

array_tile_2d = np.tile([[1, 2]], (2, 3))
print(array_tile_2d)

array_reshaped = np.arange(9).reshape((3, 3))
print(array_reshaped)

array_from_iter = np.fromiter((x * 2 for x in range(5)), dtype=int)
print(array_from_iter)

[1 2 3 4 5]
[10 20 30 40 50]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[1.         1.33333333 1.66666667 2.        ]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]]
[            nan 2.22514176e-306 7.56599807e-307]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.17117871 0.83995059 0.34979745]
 [0.74555068 0.73586759 0.83121341]]
[[5 3 7]
 [5 3 1]
 [1 1 1]]
[[-1.59764652 -0.27914577]
 [ 0.44826508  0.18484826]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[1 2 1 2 1 2]
[[1 2 1 2 1 2]
 [1 2 1 2 1 2]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 2 4 6 8]


In [ ]:
# Topic: Manipulating, Aggregating, and Combining NumPy Arrays

import numpy as np

# Manipulating Arrays

array_1d = np.arange(9)
print("Original Array:", array_1d)

array_reshaped = array_1d.reshape((3, 3))
print("Reshaped Array:\n", array_reshaped)

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Element at position (1, 2):", array_2d[1, 2])

print("Sliced Array:\n", array_2d[:2, 1:])

array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

print("Addition:", array_a + array_b)

print("Multiplication:", array_a * array_b)

print("Division:", array_a / array_b)

array_1d = np.array([1, 2, 3])
array_2d = np.array([[4, 5, 6], [7, 8, 9]])

result = array_2d + array_1d
print("Broadcasted Array:\n", result)

# Aggregating Arrays

array = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(array))

print("Mean:", np.mean(array))

array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum along columns:", np.sum(array_2d, axis=0))

print("Sum along rows:", np.sum(array_2d, axis=1))

print("Minimum:", np.min(array))

print("Maximum:", np.max(array))

print("Cumulative sum:", np.cumsum(array))

print("Cumulative product:", np.cumprod(array))

In [3]:
# Combining Arrays

array = np.array([1, 2, 3])

array_b = np.array([4, 5, 6])

concatenated_array = np.concatenate([array, array_b])
print("Concatenated Array:", concatenated_array)

array_2d_a = np.array([[1, 2], [3, 4]])
array_2d_b = np.array([[5, 6], [7, 8]])

concatenated_2d = np.concatenate([array_2d_a, array_2d_b], axis=0)
print("Concatenated 2D Array:\n", concatenated_2d)

array_a = np.array([1, 2])
array_b = np.array([3, 4])

stacked_vertically = np.vstack([array_a, array_b])
print("Stacked Vertically:\n", stacked_vertically)

stacked_horizontally = np.hstack([array_a, array_b])
print("Stacked Horizontally:", stacked_horizontally)

array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

column_stacked = np.column_stack([array_a, array_b])
print("Column Stacked Array:\n", column_stacked)

array = np.array([1, 2, 3, 4, 5, 6])

split_array = np.split(array, 3)
print("Split Array:", split_array)

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_2d = np.split(array_2d, 3, axis=0)
print("2D Split Array:\n", split_2d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = array_2d.flatten()
print("Flattened Array:", flattened_array)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])

transposed_array = array_2d.T
print("Transposed Array:\n", transposed_array)

Concatenated Array: [1 2 3 4 5 6]
Concatenated 2D Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Stacked Vertically:
 [[1 2]
 [3 4]]
Stacked Horizontally: [1 2 3 4]
Column Stacked Array:
 [[1 4]
 [2 5]
 [3 6]]
Split Array: [array([1, 2]), array([3, 4]), array([5, 6])]
2D Split Array:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
